function [] = check_hydromech(step,xm,ym,tk0,tk1,tk2,DT,APHI,vxf,vyf,pscale,ETA,ETAP,GGG,...
    GGGP,SXY0,SXX0,RHOX,RHOY,RHOFX,RHOFY,RX,RY,ETAPHI,BETTAPHI,PHI,gx,gy,...
    pr0,pf0,dt,R,L_d,S,vx,vy,qxD,qyD,pr,pf)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
close all;
disp(['CHECKING HYDROMECH INPUTS/OUTPUTS, time step =' num2str(step)]);
[xm_jl,ym_jl,tk0_jl,tk1_jl,tk2_jl,DT_jl,APHI_jl,vxf_jl,vyf_jl,pscale_jl,ETA_jl,ETAP_jl,GGG_jl,...
    GGGP_jl,SXY0_jl,SXX0_jl,RHOX_jl,RHOY_jl,RHOFX_jl,RHOFY_jl,RX_jl,RY_jl,...
    ETAPHI_jl,BETTAPHI_jl,PHI_jl,gx_jl,gy_jl,pr0_jl,pf0_jl,dt_jl,R_jl,...
    L_jl,S_jl,vx_jl,vy_jl,qxD_jl,qyD_jl,pr_jl,pf_jl] = M_1078(step);
disp(['xm' '------------------------------------------']);
[~,eps_total,f]=check(xm,xm_jl);
sgt = ['L1 error xm, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['ym' '------------------------------------------']);
[~,eps_total,f]=check(ym,ym_jl);
sgt = ['L1 error ym, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['tk0' '------------------------------------------']);
[~,eps_total,f]=check(tk0,tk0_jl);
sgt = ['L1 error tk0, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['tk1' '------------------------------------------']);
[~,eps_total,f]=check(tk1,tk1_jl);
sgt = ['L1 error tk1, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['tk2' '------------------------------------------']);
[~,eps_total,f]=check(tk2,tk2_jl);
sgt = ['L1 error tk2, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['DT' '------------------------------------------']);
[~,eps_total,f]=check(DT,DT_jl);
sgt = ['L1 error DT, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['APHI' '------------------------------------------']);
[~,eps_total,f]=check(APHI,APHI_jl);
sgt = ['L1 error APHI, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['vxf' '------------------------------------------']);
[~,eps_total,f]=check(vxf,vxf_jl);
sgt = ['L1 error vxf, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['vyf' '------------------------------------------']);
[~,eps_total,f]=check(vyf,vyf_jl);
sgt = ['L1 error vyf, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['pscale' '------------------------------------------']);
[~,~]=check(pscale,pscale_jl);
disp(['ETA' '------------------------------------------']);
[~,eps_total,f]=check(ETA,ETA_jl);
sgt = ['L1 error ETA, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['ETAP' '------------------------------------------']);
[~,eps_total,f]=check(ETAP,ETAP_jl);
sgt = ['L1 error ETAP, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['GGG' '------------------------------------------']);
[~,eps_total,f]=check(GGG,GGG_jl);
sgt = ['L1 error GGG, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['GGGP' '------------------------------------------']);
[~,eps_total,f]=check(GGGP,GGGP_jl);
sgt = ['L1 error GGGP, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['SXY0' '------------------------------------------']);
[~,eps_total,f]=check(SXY0,SXY0_jl);
sgt = ['L1 error SXY0, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['SXX0' '------------------------------------------']);
[~,eps_total,f]=check(SXX0,SXX0_jl);
sgt = ['L1 error SXX0, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['RHOX' '------------------------------------------']);
[~,eps_total,f]=check(RHOX,RHOX_jl);
sgt = ['L1 error RHOX, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['RHOY' '------------------------------------------']);
[~,eps_total,f]=check(RHOY,RHOY_jl);
sgt = ['L1 error RHOY, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['RHOFX' '------------------------------------------']);
[~,eps_total,f]=check(RHOFX,RHOFX_jl);
sgt = ['L1 error RHOFX, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['RHOFY' '------------------------------------------']);
[~,eps_total,f]=check(RHOFY,RHOFY_jl);
sgt = ['L1 error RHOFY, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['RX' '------------------------------------------']);
[~,eps_total,f]=check(RX,RX_jl);
sgt = ['L1 error RX, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['RY' '------------------------------------------']);
[~,eps_total,f]=check(RY,RY_jl);
sgt = ['L1 error RY, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['ETAPHI' '------------------------------------------']);
[~,eps_total,f]=check(ETAPHI,ETAPHI_jl);
sgt = ['L1 error ETAPHI, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['BETTAPHI' '------------------------------------------']);
[~,eps_total,f]=check(BETTAPHI,BETTAPHI_jl);
sgt = ['L1 error BETTAPHI, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['PHI' '------------------------------------------']);
[~,eps_total,f]=check(PHI,PHI_jl);
sgt = ['L1 error PHI, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['gx' '------------------------------------------']);
[~,eps_total,f]=check(gx,gx_jl);
sgt = ['L1 error gx, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['gy' '------------------------------------------']);
[~,eps_total,f]=check(gy,gy_jl);
sgt = ['L1 error gy, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['pr0' '------------------------------------------']);
[~,eps_total,f]=check(pr0,pr0_jl);
sgt = ['L1 error pr0, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['pf0' '------------------------------------------']);
[~,eps_total,f]=check(pf0,pf0_jl);
sgt = ['L1 error pf0, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['vx' '------------------------------------------']);
[~,eps_total,f]=check(vx,vx_jl);
sgt = ['L1 error vx, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['vy' '------------------------------------------']);
[~,eps_total,f]=check(vy,vy_jl);
sgt = ['L1 error vy, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['qxD' '------------------------------------------']);
[~,eps_total,f]=check(qxD,qxD_jl);
sgt = ['L1 error qxD, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['qyD' '------------------------------------------']);
[~,eps_total,f]=check(qyD,qyD_jl);
sgt = ['L1 error qyD, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['pr' '------------------------------------------']);
[~,eps_total,f]=check(pr(2:end-1,2:end-1),pr_jl(2:end-1,2:end-1));
sgt = ['L1 error pr, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
disp(['pf' '------------------------------------------']);
[~,eps_total,f]=check(pf(2:end-1,2:end-1),pf_jl(2:end-1,2:end-1));
sgt = ['L1 error pf, timestep=' num2str(step) ];
sgtitle([sgt  ', eps=' num2str(eps_total, '%e')]);
set(gcf,'color','w'); export_fig(sgt, '-pdf', '-m2');
end