module Erebus

using ArgParse
using Base.Threads
using Dates
using DocStringExtensions
using ExtendableSparse
using JLD2
using LinearAlgebra
using LinearSolve
using Logging
using ProgressMeter
using Random
using SparseArrays
using StaticArrays
using TimerOutputs
using TOML

export run_simulation, load_state, simulation_loop
export Config,
    GridConfig,
    GeometryConfig,
    TimeConfig,
    SolverConfig,
    PoroelasticConfig,
    ThermalConfig,
    ReactionConfig,
    MaterialConfig,
    OutputConfig,
    DiskConfig,
    MeltingConfig,
    VentingConfig,
    VolatilesConfig,
    EscapeConfig,
    CoreFormationConfig,
    SimulationConfig,
    default_config,
    load_config,
    validate_config,
    save_config,
    compute_iron_wustite_fO2,
    compute_water_solubility_melt,
    compute_nitrogen_solubility_melt,
    compute_organic_nitrogen_yield,
    compute_h2_solubility_melt,
    compute_nitrogen_solubility_dasgupta,
    compute_co_solubility_melt,
    compute_ch4_solubility_melt,
    compute_co2_solubility_melt,
    compute_carbon_solubility_melt,
    compute_graphite_saturation_fugacity,
    compute_sulfur_solubility_melt,
    compute_scss,
    solve_chnos_speciation,
    compute_escape_velocity,
    compute_thermal_velocity,
    compute_jeans_parameter,
    compute_jeans_escape_flux,
    compute_jeans_mass_loss_rate,
    compute_atmospheric_scale_height,
    compute_surface_atmospheric_pressure,
    evolve_atmospheric_species_inventory,
    get_species_molecular_mass,
    MASS_H2O_KG,
    MASS_H2_KG,
    MASS_N2_KG,
    MASS_NH3_KG,
    MASS_CO_KG,
    MASS_CO2_KG,
    MASS_CH4_KG,
    MASS_H2S_KG,
    MASS_S2_KG,
    MASS_SO2_KG,
    JEANS_LAMBDA_CUTOFF,
    HYDRODYNAMIC_ESCAPE_LAMBDA_LOW,
    HYDRODYNAMIC_ESCAPE_LAMBDA_CUTOFF,
    compute_species_vapor_pressure,
    compute_volatile_exsolution,
    metal_permeability,
    stokes_settling_velocity,
    weber_equilibrium_diameter,
    richardson_zaki_hindrance,
    compute_metal_melt_fraction,
    metal_segregation_velocity,
    segregation_dissipation_heating,
    metal_blended_density,
    metal_blended_conductivity,
    metal_blended_heat_capacity,
    suspension_rouse_number,
    compute_melt_fraction,
    rhocp_apparent_silicate,
    compute_melt_weakened_viscosity,
    regularized_soft_turbulence_conductivity,
    compute_disk_temperature,
    compute_snowline_radius,
    compute_radiation_htc,
    compute_disk_dispersal_weight,
    compute_solar_equilibrium_temperature,
    compute_ambient_conditions,
    compute_ice_vapor_pressure,
    compute_water_vapor_pressure,
    compute_venting_pressure,
    compute_ice_sealed_permeability,
    is_hydrofracture_breached,
    compute_face_venting_permeability,
    compute_spherical_metric_heat_source!,
    apply_radiative_surface_boundary!,
    apply_venting_surface_boundary!,
    apply_metal_segregation!,
    sink_vented_marker_porosity!,
    GridCoordinates,
    default_grid_coordinates,
    compute_adaptive_timestep,
    ThreadInterpolationBuffers,
    allocate_thread_interpolation_buffers,
    reset_thread_buffers!,
    reduce_thread_buffers!,
    setup_marker_metal_properties,
    setup_marker_volatile_properties,
    update_single_marker_volatile_exsolution!,
    update_marker_volatile_exsolution!
export Geometry, Physics, Particles, Numerics, Simulation

include("constants.jl")
# include("test_constants.jl")

if use_pardiso
    using Pardiso
else
    if Sys.isapple()
        using AppleAccelerate
    else
        # using MKL
    end
end

const to = TimerOutput()
const rgen = MersenneTwister(seed)

# Core modular components
include("config.jl")
include("coordinates.jl")
include("geometry.jl")
include("physics.jl")
include("particles.jl")
include("numerics.jl")
include("simulation.jl")

# Submodule interfaces
module Geometry
    import ..Erebus:
        setup_staggered_grid_properties,
        setup_staggered_grid_properties_helpers,
        grid_vector,
        dot4,
        grid_average,
        apply_insulating_boundary_conditions!
    export setup_staggered_grid_properties,
        setup_staggered_grid_properties_helpers,
        grid_vector,
        dot4,
        grid_average,
        apply_insulating_boundary_conditions!
end

module Physics
    import ..Erebus:
        distance,
        total,
        ktotal,
        kphi,
        ηᶠcur_inv_kᵠ,
        Q_radiogenic,
        etatotal_rocks,
        calculate_radioactive_heating,
        compute_rhocpfluidm,
        compute_ksolidm,
        compute_kfluidm,
        compute_Δtreaction,
        compute_gibbs_free_energy,
        compute_relative_enthalpy,
        compute_reaction_constant,
        compute_thermodynamic_xfer!,
        perform_thermochemical_reaction!,
        compute_shear_heating!,
        compute_adiabatic_heating!,
        compute_drained_compressibility,
        compute_biot_willis_coefficient,
        compute_skempton_coefficient,
        compute_rhofluid,
        compute_fluid_viscosity,
        compute_hydrofracture_factor,
        compute_hydrofracture_permeability,
        compute_ice_sealed_permeability,
        is_hydrofracture_breached,
        compute_disk_temperature,
        compute_snowline_radius,
        compute_radiation_htc,
        compute_spherical_metric_heat_source!,
        compute_melt_fraction,
        rhocp_apparent_silicate,
        compute_melt_weakened_viscosity,
        regularized_soft_turbulence_conductivity,
        metal_permeability,
        stokes_settling_velocity,
        weber_equilibrium_diameter,
        richardson_zaki_hindrance,
        compute_metal_melt_fraction,
        metal_segregation_velocity,
        segregation_dissipation_heating,
        metal_blended_density,
        metal_blended_conductivity,
        metal_blended_heat_capacity,
        suspension_rouse_number,
        compute_iron_wustite_fO2,
        compute_water_solubility_melt,
        compute_nitrogen_solubility_melt,
        compute_organic_nitrogen_yield,
        compute_h2_solubility_melt,
        compute_nitrogen_solubility_dasgupta,
        compute_co_solubility_melt,
        compute_ch4_solubility_melt,
        compute_co2_solubility_melt,
        compute_carbon_solubility_melt,
        compute_graphite_saturation_fugacity,
        compute_sulfur_solubility_melt,
        compute_scss,
        solve_chnos_speciation,
        compute_escape_velocity,
        compute_thermal_velocity,
        compute_jeans_parameter,
        compute_jeans_escape_flux,
        compute_jeans_mass_loss_rate,
        compute_atmospheric_scale_height,
        compute_surface_atmospheric_pressure,
        evolve_atmospheric_species_inventory,
        get_species_molecular_mass,
        MASS_H2O_KG,
        MASS_H2_KG,
        MASS_N2_KG,
        MASS_NH3_KG,
        MASS_CO_KG,
        MASS_CO2_KG,
        MASS_CH4_KG,
        MASS_H2S_KG,
        MASS_S2_KG,
        MASS_SO2_KG,
        JEANS_LAMBDA_CUTOFF
    export distance,
        total,
        ktotal,
        kphi,
        ηᶠcur_inv_kᵠ,
        Q_radiogenic,
        etatotal_rocks,
        calculate_radioactive_heating,
        compute_rhocpfluidm,
        compute_ksolidm,
        compute_kfluidm,
        compute_Δtreaction,
        compute_gibbs_free_energy,
        compute_relative_enthalpy,
        compute_reaction_constant,
        compute_thermodynamic_xfer!,
        perform_thermochemical_reaction!,
        compute_shear_heating!,
        compute_adiabatic_heating!,
        compute_drained_compressibility,
        compute_biot_willis_coefficient,
        compute_skempton_coefficient,
        compute_rhofluid,
        compute_fluid_viscosity,
        compute_hydrofracture_factor,
        compute_hydrofracture_permeability,
        compute_ice_sealed_permeability,
        is_hydrofracture_breached,
        compute_disk_temperature,
        compute_snowline_radius,
        compute_radiation_htc,
        compute_spherical_metric_heat_source!,
        compute_melt_fraction,
        rhocp_apparent_silicate,
        compute_melt_weakened_viscosity,
        regularized_soft_turbulence_conductivity,
        metal_permeability,
        stokes_settling_velocity,
        weber_equilibrium_diameter,
        richardson_zaki_hindrance,
        compute_metal_melt_fraction,
        metal_segregation_velocity,
        segregation_dissipation_heating,
        metal_blended_density,
        metal_blended_conductivity,
        metal_blended_heat_capacity,
        suspension_rouse_number,
        compute_iron_wustite_fO2,
        compute_water_solubility_melt,
        compute_nitrogen_solubility_melt,
        compute_organic_nitrogen_yield,
        compute_h2_solubility_melt,
        compute_nitrogen_solubility_dasgupta,
        compute_co_solubility_melt,
        compute_ch4_solubility_melt,
        compute_co2_solubility_melt,
        compute_carbon_solubility_melt,
        compute_graphite_saturation_fugacity,
        compute_sulfur_solubility_melt,
        compute_scss,
        solve_chnos_speciation,
        compute_escape_velocity,
        compute_thermal_velocity,
        compute_jeans_parameter,
        compute_jeans_escape_flux,
        compute_jeans_mass_loss_rate,
        compute_atmospheric_scale_height,
        compute_surface_atmospheric_pressure,
        evolve_atmospheric_species_inventory,
        get_species_molecular_mass,
        MASS_H2O_KG,
        MASS_H2_KG,
        MASS_N2_KG,
        MASS_NH3_KG,
        MASS_CO_KG,
        MASS_CO2_KG,
        MASS_CH4_KG,
        MASS_H2S_KG,
        MASS_S2_KG,
        MASS_SO2_KG,
        JEANS_LAMBDA_CUTOFF,
        HYDRODYNAMIC_ESCAPE_LAMBDA_LOW,
        HYDRODYNAMIC_ESCAPE_LAMBDA_CUTOFF,
        compute_species_vapor_pressure,
        compute_volatile_exsolution
end

module Particles
    import ..Erebus:
        setup_marker_properties,
        setup_marker_metal_properties,
        setup_marker_volatile_properties,
        update_single_marker_volatile_exsolution!,
        update_marker_volatile_exsolution!,
        setup_marker_properties_helpers,
        setup_marker_geometry_helpers,
        define_markers!,
        compute_marker_properties!,
        update_marker_viscosity!,
        setup_interpolated_properties,
        reset_interpolated_properties!,
        reset_thermochemical_properties!,
        fix_weights,
        fix_distances,
        fix,
        reduce_add_3darray!,
        interpolate_add_to_grid!,
        interpolate_to_marker!,
        interpolate_add_to_marker!,
        marker_to_basic_nodes!,
        marker_to_vx_nodes!,
        marker_to_vy_nodes!,
        marker_to_p_nodes!,
        molarfraction_marker_to_p_nodes!,
        update_p_nodes_melt_composition!,
        compute_basic_node_properties!,
        compute_vx_node_properties!,
        compute_vy_node_properties!,
        compute_p_node_properties!,
        compute_molarfraction!,
        add_vrk4,
        compute_velocities!,
        compute_rotation_rate!,
        move_markers_rk4!,
        backtrace_pressures_rk4!,
        update_marker_population_geometry!,
        replenish_markers!,
        apply_subgrid_stress_diffusion!,
        update_marker_stress!,
        apply_subgrid_temperature_diffusion!,
        update_marker_temperature!,
        update_marker_porosity!,
        ThreadInterpolationBuffers,
        allocate_thread_interpolation_buffers,
        reset_thread_buffers!,
        reduce_thread_buffers!
    export setup_marker_properties,
        setup_marker_metal_properties,
        setup_marker_volatile_properties,
        update_single_marker_volatile_exsolution!,
        update_marker_volatile_exsolution!,
        setup_marker_properties_helpers,
        setup_marker_geometry_helpers,
        define_markers!,
        compute_marker_properties!,
        update_marker_viscosity!,
        setup_interpolated_properties,
        reset_interpolated_properties!,
        reset_thermochemical_properties!,
        fix_weights,
        fix_distances,
        fix,
        reduce_add_3darray!,
        interpolate_add_to_grid!,
        interpolate_to_marker!,
        interpolate_add_to_marker!,
        marker_to_basic_nodes!,
        marker_to_vx_nodes!,
        marker_to_vy_nodes!,
        marker_to_p_nodes!,
        molarfraction_marker_to_p_nodes!,
        update_p_nodes_melt_composition!,
        compute_basic_node_properties!,
        compute_vx_node_properties!,
        compute_vy_node_properties!,
        compute_p_node_properties!,
        compute_molarfraction!,
        add_vrk4,
        compute_velocities!,
        compute_rotation_rate!,
        move_markers_rk4!,
        backtrace_pressures_rk4!,
        update_marker_population_geometry!,
        replenish_markers!,
        apply_subgrid_stress_diffusion!,
        update_marker_stress!,
        apply_subgrid_temperature_diffusion!,
        update_marker_temperature!,
        update_marker_porosity!,
        ThreadInterpolationBuffers,
        allocate_thread_interpolation_buffers,
        reset_thread_buffers!,
        reduce_thread_buffers!
end

module Numerics
    import ..Erebus:
        setup_gravitational_lse,
        setup_hydromechanical_lse,
        setup_thermal_lse,
        initialize_pardiso!,
        get_viscosities_stresses_density_gradients!,
        is_gravitational_boundary,
        assemble_gravitational_lse!,
        assemble_gravitational_rhs!,
        process_gravitational_solution!,
        compute_gravity_solution!,
        assemble_hydromechanical_lse!,
        process_hydromechanical_solution!,
        recompute_bulk_viscosity!,
        compute_Aϕ!,
        compute_fluid_velocities!,
        compute_displacement_timestep,
        compute_adaptive_timestep,
        compute_stress_strainrate!,
        symmetrize_p_node_observables!,
        compute_nodal_adjustment!,
        positive_max!,
        finalize_plastic_iteration_pass!,
        assemble_thermal_lse!,
        perform_thermal_iterations!,
        finalize_thermochemical_iteration_pass,
        compute_thermochemical_iteration_outcome,
        apply_radiative_surface_boundary!,
        apply_venting_surface_boundary!,
        apply_metal_segregation!,
        compute_face_venting_permeability
    export setup_gravitational_lse,
        setup_hydromechanical_lse,
        setup_thermal_lse,
        initialize_pardiso!,
        get_viscosities_stresses_density_gradients!,
        is_gravitational_boundary,
        assemble_gravitational_lse!,
        assemble_gravitational_rhs!,
        process_gravitational_solution!,
        compute_gravity_solution!,
        assemble_hydromechanical_lse!,
        process_hydromechanical_solution!,
        recompute_bulk_viscosity!,
        compute_Aϕ!,
        compute_fluid_velocities!,
        compute_displacement_timestep,
        compute_adaptive_timestep,
        compute_stress_strainrate!,
        symmetrize_p_node_observables!,
        compute_nodal_adjustment!,
        positive_max!,
        finalize_plastic_iteration_pass!,
        assemble_thermal_lse!,
        perform_thermal_iterations!,
        finalize_thermochemical_iteration_pass,
        compute_thermochemical_iteration_outcome,
        apply_radiative_surface_boundary!,
        apply_venting_surface_boundary!,
        apply_metal_segregation!,
        compute_face_venting_permeability
end

module Simulation
    import ..Erebus:
        s_to_Ma,
        setup_dynamic_simulation_parameters,
        save_state,
        load_state,
        simulation_loop,
        parse_commandline,
        run_simulation
    export s_to_Ma,
        setup_dynamic_simulation_parameters,
        save_state,
        load_state,
        simulation_loop,
        parse_commandline,
        run_simulation
end

module Config
    import ..Erebus:
        GridConfig,
        GeometryConfig,
        TimeConfig,
        SolverConfig,
        PoroelasticConfig,
        ThermalConfig,
        ReactionConfig,
        MaterialConfig,
        OutputConfig,
        DiskConfig,
        MeltingConfig,
        VentingConfig,
        VolatilesConfig,
        EscapeConfig,
        CoreFormationConfig,
        SimulationConfig,
        default_config,
        load_config,
        validate_config,
        save_config
    export GridConfig,
        GeometryConfig,
        TimeConfig,
        SolverConfig,
        PoroelasticConfig,
        ThermalConfig,
        ReactionConfig,
        MaterialConfig,
        OutputConfig,
        DiskConfig,
        MeltingConfig,
        VentingConfig,
        VolatilesConfig,
        EscapeConfig,
        CoreFormationConfig,
        SimulationConfig,
        default_config,
        load_config,
        validate_config,
        save_config
end

end # module Erebus
