# Numerics module components
include("numerics/lse_setup.jl")
include("numerics/gravity.jl")
include("numerics/stokes_darcy.jl")
include("numerics/timestep.jl")
include("numerics/plasticity.jl")
include("numerics/thermal.jl")
include("numerics/segregation.jl")
include("numerics/p2m_tiled.jl")
include("numerics/iterative_solver.jl")
include("numerics/multigrid.jl")
include("numerics/gpu_kernels.jl")
