# Physics module components
include("physics/materials_metric.jl")
include("physics/radioactivity.jl")
include("physics/serpentinization.jl")
include("physics/dissipation.jl")
include("physics/poroelasticity.jl")
include("physics/disk_venting.jl")
include("physics/melting_convection.jl")
include("physics/hydrothermal.jl")
include("physics/solubility_speciation.jl")
include("physics/escape.jl")
include("physics/core_dynamics.jl")
include("physics/metal_partitioning.jl")
include("physics/volatile_mixtures.jl")
