# Simulation module components
include("simulation/transfers.jl")
include("simulation/workspace.jl")
include("simulation/state.jl")
include("simulation/checkpoint.jl")
include("simulation/steps/accrete.jl")
include("simulation/steps/radiogenic_heating.jl")
include("simulation/steps/interpolate_markers_to_grid.jl")
include("simulation/steps/solve_gravity.jl")
include("simulation/steps/vent_and_degas.jl")
include("simulation/steps/evolve_atmosphere.jl")
include("simulation/steps/advect_markers.jl")
include("simulation/steps/replenish.jl")
include("simulation/loop.jl")
include("simulation/cli.jl")
include("simulation/ensemble.jl")
